### ISSUE TITLE
Question: Keep Chromium open in case of errors?

### ISSUE THREAD

**Issue by tisba** [drdla/export-amazon-invoices#1]
For some reason I get a "Could not log in" error.

Is there an option I can set, so that the Browser stays open so I can further inspect the problem?

**Comment by drdla** [comment]
There is now, see https://github.com/drdla/export-amazon-invoices/commit/96c5d041e9fad2f81f5cabeaff78b53c73db679a

I could even have referenced this issue in my commit ...

Anyhow: after running it myself, I found the reason for the problem.
Amazon has split its login process into two steps. I updated the code to reflect this change, but in a quick test I noticed that they also require a one-time code when a login from a new device is detected, so my change may not yet be sufficient.
But feel free to give it a try. PRs welcome.
